In [14]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn

In [15]:
!ls test-1/no_ResNet2d-telomerase/

test_log.csv  train_log.csv  valid_with_test  weights.pmt

In [16]:
train = []
train.append(pd.read_csv('test-1/no_ResNet2d-telomerase/train_log.csv'))
train.append(pd.read_csv('test-2/no_ResNet2d-telomerase/train_log.csv'))
train.append(pd.read_csv('test-3/no_ResNet2d-telomerase/train_log.csv'))


train_valid = []
train_valid.append(pd.read_csv('test-1/no_ResNet2d-telomerase/valid_with_test/train_log.csv'))
train_valid.append(pd.read_csv('test-2/no_ResNet2d-telomerase/valid_with_test/train_log.csv'))
train_valid.append(pd.read_csv('test-3/no_ResNet2d-telomerase/valid_with_test/train_log.csv'))

In [17]:
display(train[0] - train[1])
display(train[0] - train[2])
display(train[1] - train[2])

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000      0.0000   -0.0001        -0.0001      0.0000
1      0    0.0000      0.0000    0.0001         0.0000      0.0001
2      0    0.0003     -0.0001    0.0004        -0.0003      0.0000
3      0   -0.0001      0.0000   -0.0003        -0.0001      0.0000
4      0    0.0002      0.0000   -0.0019        -0.0001      0.0001

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0   -0.0001         0.0    0.0000         0.0001      0.0000
1      0   -0.0001         0.0    0.0002         0.0006      0.0000
2      0    0.0001         0.0    0.0003        -0.0002      0.0000
3      0   -0.0001         0.0   -0.0002         0.0002      0.0000
4      0    0.0001         0.0   -0.0003        -0.0002      0.0001

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0   -0.0001      0.0000    0.0001         0.0002      0.0000
1      0   -0.0001      0.0000    0.0001         0.0006     -0.0001
2      0   -0.0002      0.0001   -0.0001         0.0001      0.0000
3      0    0.0000      0.0000    0.0001         0.0003      0.0000
4      0   -0.0001      0.0000    0.0016        -0.0001      0.0000

In [18]:
display(train[0] - train_valid[0])
display(train[1] - train_valid[1])
display(train[2] - train_valid[2])

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000      0.0000   -0.0001         0.0001      0.0000
1      0   -0.0001      0.0000   -0.0003        -0.0001      0.0000
2      0    0.0001     -0.0001    0.0004        -0.0010      0.0000
3      0    0.0001      0.0000    0.0007         0.0003      0.0000
4      0    0.0001      0.0000   -0.0018        -0.0003      0.0001

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000      0.0000    0.0002         0.0004      0.0000
1      0    0.0000      0.0000    0.0003         0.0002     -0.0001
2      0    0.0000      0.0001   -0.0008         0.0002      0.0000
3      0    0.0000      0.0000    0.0003         0.0004      0.0000
4      0   -0.0002      0.0000    0.0004        -0.0005      0.0000

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0001         0.0   -0.0002        -0.0001      0.0000
1      0    0.0001         0.0   -0.0002        -0.0005      0.0001
2      0    0.0001         0.0    0.0003        -0.0005      0.0000
3      0    0.0001         0.0    0.0001         0.0001      0.0000
4      0    0.0001         0.0   -0.0016        -0.0004      0.0000

In [19]:
display(train_valid[0] - train_valid[1])
display(train_valid[0] - train_valid[2])
display(train_valid[1] - train_valid[2])

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000      0.0000    0.0002         0.0002         0.0
1      0    0.0001      0.0000    0.0007         0.0003         0.0
2      0    0.0002      0.0001   -0.0008         0.0009         0.0
3      0   -0.0002      0.0000   -0.0007         0.0000         0.0
4      0   -0.0001      0.0000    0.0003        -0.0003         0.0

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000      0.0000   -0.0001        -0.0001      0.0000
1      0    0.0001      0.0000    0.0003         0.0002      0.0001
2      0    0.0001      0.0001    0.0002         0.0003      0.0000
3      0   -0.0001      0.0000   -0.0008         0.0000      0.0000
4      0    0.0001      0.0000   -0.0001        -0.0003      0.0000

   epoch  train_f1  train_loss  valid_f1  valid_f1_post  valid_loss
0      0    0.0000         0.0   -0.0003        -0.0003      0.0000
1      0    0.0000         0.0   -0.0004        -0.0001      0.0001
2      0   -0.0001         0.0    0.0010        -0.0006      0.0000
3      0    0.0001         0.0   -0.0001         0.0000      0.0000
4      0    0.0002         0.0   -0.0004         0.0000      0.0000

Analisis de test

In [24]:
test = []
test.append(pd.read_csv('test-1/no_ResNet2d-telomerase/test_log.csv'))
test.append(pd.read_csv('test-2/no_ResNet2d-telomerase/test_log.csv'))
test.append(pd.read_csv('test-3/no_ResNet2d-telomerase/test_log.csv'))


test_valid = []
test_valid.append(pd.read_csv('test-1/no_ResNet2d-telomerase/valid_with_test/test_log.csv'))
test_valid.append(pd.read_csv('test-2/no_ResNet2d-telomerase/valid_with_test/test_log.csv'))
test_valid.append(pd.read_csv('test-3/no_ResNet2d-telomerase/valid_with_test/test_log.csv'))
for t in test: display(t)
print('valid')
for t in test_valid: display(t)

      f1  f1_post   loss
0  0.139    0.184  0.033

      f1  f1_post   loss
0  0.139    0.183  0.033

     f1  f1_post   loss
0  0.14    0.183  0.033

valid

      f1  f1_post   loss
0  0.139    0.184  0.033

      f1  f1_post   loss
0  0.139    0.184  0.033

      f1  f1_post   loss
0  0.139    0.182  0.033

In [21]:
display(test[0] - test[1])
display(test[0] - test[2])
display(test[1] - test[2])

    f1  f1_post  loss
0  0.0    0.001   0.0

      f1  f1_post  loss
0 -0.001    0.001   0.0

      f1  f1_post  loss
0 -0.001      0.0   0.0

In [22]:
display(test_valid[0] - test_valid[1])
display(test_valid[0] - test_valid[2])
display(test_valid[1] - test_valid[2])

    f1  f1_post  loss
0  0.0      0.0   0.0

    f1  f1_post  loss
0  0.0    0.002   0.0

    f1  f1_post  loss
0  0.0    0.002   0.0